from enum import Enum


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class AlertType(str, Enum):
    STRUCTURING = "STRUCTURING"
    THRESHOLD = "THRESHOLD"
    HIGH_RISK_COUNTRY = "HIGH_RISK_COUNTRY"
    WATCHLIST_MATCH = "WATCHLIST_MATCH"
    RAPID_MOVEMENT = "RAPID_MOVEMENT"
    ROUND_AMOUNT = "ROUND_AMOUNT"
    DORMANT_ACCOUNT = "DORMANT_ACCOUNT"
    COUNTERPARTY_CONCENTRATION = "COUNTERPARTY_CONCENTRATION"
    PROFILE_DEVIATION = "PROFILE_DEVIATION"
    FLOW_THROUGH = "FLOW_THROUGH"
